### ISSUE TITLE
Missing files in subdirectories

### ISSUE THREAD

**Issue by ceedubs** [tpolecat/tut#100]
I'm using tut along with sbt-site. I have a tut dir that looks like:

```
docs/src/main/tut/
  a.md
  b.md
  subdir/
    c.md
```

Everything works splendidly for `a.md` and `b.md`. They result in `docs/target/site/tut/a.html` and `docs/target/site/tut/b.html` respectively. `c.md` gets compiled via tut, tut correctly complains if there are errors, and I see a generated `docs/target/site/tut/subdir/` directory. But that directory is empty, so there's no `c.html` to navigate to.

**Comment by tpolecat** [comment]
Well that's weird. Does it work if you don't do the sbt-site thing? @stew added that doc but I don't know how it works.

There's a [test](https://github.com/tpolecat/tut/tree/master/tests/src/sbt-test/tut/test-06-walk) for this exact structure so this is very curious.

**Comment by ceedubs** [comment]
Hah even down to the filenames pretty much. Okay I think this is probably an error outside of tut land. Sorry for the false alarm. I'll dig deeper at some point and I can reopen this issue if evidence seems to be pointing to tut.

**Comment by ceedubs** [comment]
I see what's going on here. PR incoming.
