### ISSUE TITLE
Don't rebuild files that haven't changed

### ISSUE THREAD

**Issue by noelwelsh** [tpolecat/tut#109]
Tut currently rebuilds all the files in a project, even if they haven't changed since the last build. This is making building [Creative Scala](https://github.com/underscoreio/creative-scala) rather painful. It currently takes about 10 minutes (and sucks up lots of battery) to build the book. Can we be more intelligent about rebuilding files? Does `sbt` provide machinery that we can utilise to do this?

**Comment by ceedubs** [comment]
This is a duplicate of #64.

**Comment by noelwelsh** [comment]
Oops. I'll close this one.
