### ISSUE TITLE
tut uses Console.setOut, which is deprecated

### ISSUE THREAD

**Issue by SethTisue** [tpolecat/tut#144]
this is causing tut to fail in the Scala 2.13 community build ([example](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/237/consoleFull)), since https://github.com/scala/scala/pull/5683 removed this and a bunch of other deprecated stuff

the replacement is `Console.withOut`, which exists even in Scala 2.10. I was going to do a PR but the `IO` stuff in `Tut.scala` took it out of quickie territory.

incidentally if you fix this and add `import language.higherKinds` to the top of Zed.scala, I think you'll be able to compile with `-feature -deprecation -Xfatal-warnings`, which is good bragging rights at parties, or so I'm told.

**Comment by tpolecat** [comment]
Hell. `withOut` makes it harder to do in functional style because the argument has to be a side-effect. Thanks, I'll get it working somehow.

**Comment by tpolecat** [comment]
Ok, I added a new IO primitive to handle `.withOut` and fixed other warnings so I can compile with all the flags I like to tell people to use. The commit is 46eb7b8d4576581fdf1256b46c4ffcab9e22a29d if you want to try it, or point me to something that explains how to build against 2.13 and I can give it a go.

**Comment by SethTisue** [comment]
I have now merged that change into our fork of tut (forked because dbuild and bintray-sbt don't get along). I'll come back here and let you know once the next nightly community build run works or not.

**Comment by tpolecat** [comment]
Cool, thanks!

**Comment by SethTisue** [comment]
(note that building almost anything real against 2.13 is too awkward without dbuild, since there aren't any libraries published against 2.13 yet, since there isn't even a 2.13.0-M1 yet)

**Comment by SethTisue** [comment]
```
[info] Project tut---------------------: SUCCESS (project rebuilt ok)
```

**Comment by tpolecat** [comment]
![image](https://cloud.githubusercontent.com/assets/1200131/23445617/8263ffd8-fdf1-11e6-9490-50d9fea935de.png)
