### ISSUE TITLE
v0.5.1 doesn't actually fix #155

### ISSUE THREAD

**Issue by durban** [tpolecat/tut#164]
According to the changelog, v0.5.1 fixes #155 (`tut-core` is included in the POM as a dependency). However, the tag `v0.5.1` doesn't actually include the code which fixes the problem: https://github.com/tpolecat/tut/blob/v0.5.1/plugin/src/main/scala/tut/TutPlugin.scala#L20 (this can also be verified by looking at the Git commit graph, or by using the artifacts released as 0.5.1).

**Comment by tpolecat** [comment]
oh what the hell. ugh

**Comment by tpolecat** [comment]
very weird, I don't know how I botched that.

**Comment by durban** [comment]
Thanks, v0.5.2 indeed fixed it.
