### ISSUE TITLE
Feature Request: Provide modifier to pass output without code block

### ISSUE THREAD

**Issue by metasim** [tpolecat/tut#172]
Useful for code that generates markdown as it's output, e.g. table generation.

**Comment by metasim** [comment]
In principle, would you accept a PR for this?

**Comment by tpolecat** [comment]
Sure, but you might want to sketch out the details first to be sure we're on the same page. There are a lot of details, like where doe the files go, what are the paths relative to, etc.

**Comment by metasim** [comment]
I was thinking of just a [modifier](https://github.com/tpolecat/tut/blob/master/core/src/main/scala/tut/Modifier.scala#L5), say `passthrough`, whereby the block contents would work just like `evaluated` but [skips the writing of the code fence](https://github.com/tpolecat/tut/blob/master/core/src/main/scala/tut/Tut.scala#L70). That's it.

**Comment by metasim** [comment]
Happy to modify the PR as you see fit.

**Comment by metasim** [comment]
Addressed by #188
