### ISSUE TITLE
0.6.0 release is not documented

### ISSUE THREAD

**Issue by kmizu** [tpolecat/tut#179]
Now, I currently use sbt 1.0.0 and found [0.6.0](https://dl.bintray.com/sbt/sbt-plugin-releases/org.tpolecat/tut-plugin/scala_2.12/sbt_1.0/0.6.0/) is released for sbt 1.0.0.  If it is documented, users of sbt 1.0.0 will be happy.

**Comment by tpolecat** [comment]
It is mentioned on the README … where else would it be helpful to mention it?

**Comment by kmizu** [comment]
I missed that, sorry.
