### ISSUE TITLE
Behavior change post 0.5.0

### ISSUE THREAD

**Issue by kailuowang** [tpolecat/tut#193]
for some reason `tut` post `0.5.0` is taking scalacOptions in `Compile, console`
I suspect that this causes it to compile scala code differently, because scalameta no longer works in `tut` post `0.5.0` (with the exact same CLI run parameters though) 

In the following `build.sbt`, with `tut` 0.5.0 plugin, the kind project plugin no longer appears in the tut CLI run command args. Removing the line `scalacOptions in (Compile, console) := Seq()` will add it back, but this line doesn't have that effect on `tut` 0.4.x
 

```scala
lazy val root = (project in file("."))
 .enablePlugins(TutPlugin)
  .settings(
    inThisBuild(List(
      scalaVersion := "2.12.3"
    )),
    name := "Hello",
    addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.4"),
  //tutSettings,
  scalacOptions in (Compile, console) := Seq() // this line disables KP or any other compiler plugin in tut 0.5.0+
 )
~

**Comment by suhasgaddam** [comment]
I also stumbled on this while trying to figure out why macros weren't being expanded in my documentation.

For the sbt 1.0 plugin: https://github.com/tpolecat/tut/blob/master/plugin/src/main/scala/tut/TutPlugin.scala#L44

[`git blame`](https://github.com/tpolecat/tut/commit/adf668ae3fb702e9b46e611f123afc79023550ff#diff-26125911e8ac81c108bdf2fd4ad22f2fR81) first occurrence

**Comment by kailuowang** [comment]
Ah, thank you @suhasgaddam, that explains, it used to inherit scalacOption from `test`, now it's from `console`. Scalameta doesn't work in console, can we change it back?
