### ISSUE TITLE
Get things working on 2.13

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/tut#205]
There were some changes to the REPL API in 2.13 that will probably require version-specific source, so we need to set that up. And also figure out how to get it working with 2.13.

**Comment by SethTisue** [comment]
PR: #216

**Comment by SethTisue** [comment]
over at https://github.com/typelevel/cats/issues/2267#issuecomment-403100785, @BennyHill says tut is now one of the next missing pieces to get cats published for 2.13.0-M4

**Comment by ghost** [comment]
Thanks!!
