### ISSUE TITLE
Multiline statements with leading dot

### ISSUE THREAD

**Issue by skaldarnar** [tpolecat/tut#237]
Hi, 

I'm wondering whether tut supports to break statements over multiple lines with a leading dot on each line. The target code looks something like this:
```scala
val xs = List(1,2,3)
  .map(_ * 2)
  .filter(_ > 3)
```
Unfortunately, this fails with "error: illegal start of definition". Keeping the dots on the previous line works nicely:
```scala
val xs = List(1,2,3).
  map(_ * 2).
  filter(_ > 3)
```

**Comment by tpolecat** [comment]
Yeah, the REPL doesn't allow you to do this. You can do it with braces:

```scala
val xs = {
  List(1,2,3)
    .map(_ * 2)
    .filter(_ > 3)
}
```
