### ISSUE TITLE
Upgrading sbt plugin from 0.6.7 to 0.6.8 causes ClassCastException

### ISSUE THREAD

**Issue by cb372** [tpolecat/tut#240]
[cb372/scalacache](https://github.com/cb372/scalacache) uses tut via the sbt-microsites plugin. The sbt version is 1.2.1.

After bumping tut-plugin from 0.6.7 to 0.6.8, sbt now throws a ClassCastException at startup. The full stack trace is available on [the Travis log](https://travis-ci.org/cb372/scalacache/jobs/446920578#L909).

It's quite mysterious. The only changes I see in the diff are around upgrading the version of sbt used to build the plugin itself. I don't understand how that could cause this exception.

/cc @ChristopherDavenport any ideas?

**Comment by aeons** [comment]
Seeing the same in [http4s](https://github.com/http4s/http4s/pull/2209).

**Comment by tpolecat** [comment]
Huh.

**Comment by tpolecat** [comment]
I only use tut transitively through sbt-microsites … I don't pull in the tut plugin directly. I don't make any bincompat promises although I don't know why changing the sbt version would have made a difference.

So does it work if you just remove the dependency?

**Comment by fthomas** [comment]
I use tut directly without sbt-microsites and have observed this error. It also seems like [most of the PRs @scala-steward created for updating tut to 0.6.8 failed](https://github.com/search?l=Scala&q=author%3Ascala-steward+is%3Apr+"Update+tut+to+0.6.8"+&type=Issues).

**Comment by tpolecat** [comment]
I'll try another release built with 1.2.6 and see if that helps ... ????

**Comment by tpolecat** [comment]
Can you guys try with 0.6.9?

**Comment by fthomas** [comment]
0.6.9 works for me! Just merged a bunch of PRs where 0.6.8 failed. Thanks, @tpolecat!

**Comment by tpolecat** [comment]
Whew, cool. Thanks for your help!

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/4299 :thinking:

**Comment by aeons** [comment]
I think this can be closed now.
