### ISSUE TITLE
Incompatible with `sbt-1.3.0-RC1`

### ISSUE THREAD

**Issue by gvolpe** [tpolecat/tut#252]
Hi Rob,

I experienced a (binary?) issue when upgrading `sbt`. Did it happen to you by any chance?

```
[tut] compiling: /workspace/oss/fs2-rabbit/site/src/main/tut/examples/sample-mult-connections.md
[error] (run-main-2) java.lang.VerifyError: class scala.tools.nsc.Global overrides final method isDeveloper.()Z
[error] java.lang.VerifyError: class scala.tools.nsc.Global overrides final method isDeveloper.()Z
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
```

Here's the full CI build: https://circleci.com/gh/profunktor/fs2-rabbit/32

Thanks!

**Comment by tpolecat** [comment]
Ugh, no, I haven't seen that. @eed3si9n any ideas?

**Comment by gvolpe** [comment]
The same happens with `sbt-1.3.0-RC2`. /cc @eed3si9n

**Comment by eed3si9n** [comment]
```
> [error] (run-main-2) java.lang.VerifyError: class scala.tools.nsc.Global overrides final method isDeveloper.()Z
```

Does this happen on both JDK 8 and 11?
Do we know who's doing the overriding?

**Comment by gvolpe** [comment]
I only tried with JDK 8.

**Comment by eed3si9n** [comment]
I wonder if this is to do with Scala version mismatch. Scala library is designed for binary compatibility, but Scala compiler is not.

**Comment by gvolpe** [comment]
That's a good question. Hopefully Rob can provide more insights. 

As a side note, this happened sometime ago with `tut` and `scribe` but until this day the cause remains a mystery... https://github.com/outr/scribe/issues/80

**Comment by tpolecat** [comment]
> Do we know who's doing the overriding?

It's not me, it's something in the compiler. I'm at Scala Days so I'm not going to have a chance to look at this for a while. The workaround is to just run your docs in 2.12 … everyone using 2.13 is cross-compiling anyway so it should be ok for most people for now, I hope.

**Comment by gvolpe** [comment]
No problems, enjoy the conference!

**Comment by gvolpe** [comment]
> The workaround is to just run your docs in 2.12 

Mmm I'm using Scala 2.12.8, not sure I understand this. 

```
[info] Running tut.TutMain /home/circleci/repo/site/src/main/tut /home/circleci/repo/site/target/scala-2.12/ ....
```

**Comment by eed3si9n** [comment]
I bumped to sbt 1.3.0 in https://github.com/tpolecat/tut/pull/262/commits/64a387dadd77fa5644351f0ef609b5f569d3ee13, and it seems to work ok at least locally.

**Comment by gvolpe** [comment]
Thanks @eed3si9n ! I can confirm this problem is solved with the latest `tut` and `sbt`.
