### ISSUE TITLE
Assert that example fails to compile

### ISSUE THREAD

**Issue by ceedubs** [tpolecat/tut#28]
Currently tut has the `:nofail` modifier that will allow examples that fail to compile. I think I always either want to ensure that a given example _does_ compile or that it _does not_ compile. I don't think I ever want to show its output but not care whether or not it compiles.

For example, if I'm showing off my type-safe `===` operator, I probably want one example that shows that `1 === 1` evaluates to `true` and one that shows that `1 == 2` evaluates to `false`. I probably want another one to show that `1 == "1"` doesn't even compile. If I use `:nofail`, I won't be warned if I have a bug and my example actually _does_ compile.

What do you think about a `tut:fail` or `tut:fails` or similar modifier that will only fail if the example _does_ compile?

**Comment by ceedubs** [comment]
On second thought, `fail` wouldn't be a very good name for this feature if you think about it in relation to the current `nofail` modifier. I guess you could do `:assertFails` or something.

**Comment by tpolecat** [comment]
Yes, agreed. This is a very good idea. I'm not sure the REPL distinguishes "didn't compile" from "threw an exception" but if so then it might be worthwhile to allow the user to distinguish them as well. In any case I'll mess around with it and see how it looks. Thanks!

**Comment by jedesah** [comment]
+1

I think `nofail` should be dropped in favor of `fail` with the above mentioned behavior. If one does not care whether if fails or succeeds, then they can simply not use `tut`.
