### ISSUE TITLE
Truncated results cause issues

### ISSUE THREAD

**Issue by ceedubs** [tpolecat/tut#29]
See [here](https://gist.githubusercontent.com/ceedubs/2d1b328a97a63f5a6778/raw/6b720fb8db9b45a2a663065e47bb54ef4a81346d/some-tut-doc.md).

The result ends up looking something like this:
![screen shot 2015-03-10 at 11 01 45 am](https://cloud.githubusercontent.com/assets/977929/6577500/e0558348-c714-11e4-8e4a-4b5213245dd7.png)

**Comment by tpolecat** [comment]
I'm guessing the REPL is using some kind of hacked up output stream that truncates long lines. I'll see what I can figure out ... I already have three hacked up streams, why not one more?

**Comment by tpolecat** [comment]
Ugh. The problem is that there's no newline after truncated output. If you try this in the normal REPL you will see this (note the lack of a newline before the final prompt):

```
scala> "a" * 10
res0: String = aaaaaaaaaa

scala> "a" * 10000
res1: String = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
scala> 
```

So in order to detect this case I think I need to keep track of the last `Char` written to the output stream, and check after `Results.Success` and insert a newline as needed.

**Comment by tpolecat** [comment]
No me gusta.

**Comment by ceedubs** [comment]
:\
