### ISSUE TITLE
only recompile tut blocks in .md files affected by source changes?

### ISSUE THREAD

**Issue by refried** [tpolecat/tut#30]
Somehow :-)

**Comment by tpolecat** [comment]
Yeah I have wondered about doing this, maybe by generating a `.scala` source file from each `.md` and then somehow (as you say) asking sbt whether they need to be recompiled or not. I'll ask Josh or Eugene at Scala Days and see how hard it would be.

**Comment by refried** [comment]
Yeah, that's what I was thinking, but I figured you'd have an equal or better idea :-)

**Comment by ceedubs** [comment]
I think this and #64 (which has a bit more discussion) are duplicates.
