### ISSUE TITLE
tut:silent inserts newlines in between lines

### ISSUE THREAD

**Issue by longcao** [tpolecat/tut#31]
Hi there! First things first: thanks for publishing this plugin, it's just what I was looking for.

I've got a block of code that I'd like to keep as noise-free as possible, so I want `tut` to output only the relevant lines (and nothing more like returned statements), but `tut:silent` inserts newlines in between:

```tut:silent
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.{ Await, Future }
```

turns into:
```scala
import scala.concurrent.duration._

import scala.concurrent.ExecutionContext.Implicits.global

import scala.concurrent.{ Await, Future }
```

but I just want:
```scala
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.{ Await, Future }
```

Is there any way to make that happen or is it by design?

**Comment by tpolecat** [comment]
Yep, that's irritating isn't it? It also removes newlines in some other cases. I'll see if I can straighten it out in the next version. Thanks!

**Comment by longcao** [comment]
Only a little bit :) Thanks for the quick response. Looking forward to it!
