### ISSUE TITLE
tut fails if there are any directories under src/main/tut

### ISSUE THREAD

**Issue by nightscape** [tpolecat/tut#35]
As mentioned in the docs, tut tries to read all the files (which seems to include directories) under `src/main/tut`.
This leads to an exception like the following if any directories are present in `src/main/tut`:
```
[info] Running tut.TutMain /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut /Users/moe/Workspaces/scala/bayes-scala/doc/target/scala-2.10/tut
[tut] compiling: /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut/1d_kalman_filter
[error] (run-main-3) java.io.FileNotFoundException: /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut/1d_kalman_filter (Is a directory)
```

A related problem occurs if there are non-md files like png images in `src/main/tut`:
```
[info] Running tut.TutMain /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut /Users/moe/Workspaces/scala/bayes-scala/doc/target/scala-2.10/tut
[tut] compiling: /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut/1d_kalman_filter.md
[tut] compiling: /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut/clutter_problem.md
[tut] compiling: /Users/moe/Workspaces/scala/bayes-scala/doc/src/main/tut/clutter_problem.png
[error] (run-main-5) java.nio.charset.MalformedInputException: Input length = 1
```

Would it be possible to run tut only against `.md` files?

Thanks!
  Martin

**Comment by tpolecat** [comment]
Hi, yes the specification is perhaps too rigid. In practice it's only `.md` files that you want **tut** to look at, so maybe it should just copy everything else blindly. And recursing into subdirs makes sense as well. I'll look into this for the next version. Thanks!

**Comment by tpolecat** [comment]
Ok, my plan here is to make tut recurse and and mirror the entire subtree in `tutSourceDirectory` but only interpret files that match `tutPattern` which will default to something like `.*\.(md|html|txt)$`.
