### ISSUE TITLE
`libraryDependencies ` in `tutSettings ` should be scoped

### ISSUE THREAD

**Issue by jto** [tpolecat/tut#36]
So I'm not exactly an expert in dependencies scopes, but it seems that tut should not be transitively pulled if you use a Jar of a library depending on it.

That's especially problematic in Play projects because  of [this](https://github.com/etorreborre/specs2/issues/296).

**Comment by tpolecat** [comment]
Yeah I guess it should be scoped to `(Compile, doc)`. **tut** has no dependencies anymore so it shouldn't be a problem in practice, but it certainly shouldn't be added to transitive dependencies. I'll look into this, Thanks.

**Comment by tpolecat** [comment]
This is remarkably hard. I'll try scoping it to `% "test"` and see if that works.
