### ISSUE TITLE
Link tut to the sbt organization in bintray

### ISSUE THREAD

**Issue by dwijnand** [tpolecat/tut#54]
You might be interested in linking tut to the sbt organization in bintray so that there wouldn't be a need to add any resolver.

See http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization

**Comment by tpolecat** [comment]
Ok good idea, I didn't know you could do that.

**Comment by dwijnand** [comment]
Duplicated by #71.
