### ISSUE TITLE
:paste option

### ISSUE THREAD

**Issue by shajra-cs** [tpolecat/tut#62]
It would be nice to have a :paste option that would make the entire fence have
the same semantic as a REPL :paste, so we could define companion objects nicely
without boilerplate:

``````
```tut:paste
class A
object A
```
``````

which should probably just yield the normal REPL response:

``````
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

class A
object A

// Exiting paste mode, now interpreting.

defined class A
defined object A
```
``````

And it should mix fine with other modifiers like :silent and :invisible
ideally.

**Comment by ceedubs** [comment]
I also found myself wanting to define a companion object in a tut block at one point. A `:paste` feature like this came to mind. If it makes the implementation easier (though I don't know that it would), I personally would be fine with this only working in a `:silent`-like mode.

**Comment by davegurnell** [comment]
@tpolecat @ceedubs:

@daniashers and I have been chatting about this. Just in case we get ambitious and try to implement it, what do you think would be a good strategy? Is there a direct equivalent of `:paste` on the `IMain` class? Or would we insert some artificial wrapper like this:

```tut:paste
case class Foo()
object Foo
```

becomes:

```tut:silent
object randomnamehere {
case class Foo()
object Foo
}
import randomnamehere._
```
