### ISSUE TITLE
Incomplete code in tut sheds doesn't fail

### ISSUE THREAD

**Issue by ceedubs** [tpolecat/tut#65]
Discovered in version 0.4.0.

If a tut shed ends when a normal REPL would prompt for more input, tut doesn't complain that the code is incomplete.

example input (I'm using apostophes because I can't figure out how to escape backticks in GitHub markdown):

```
'''tut
{
'''
```

what I see in output:

```
scala>   {
```

I seem to forget closing braces and hit this often :)

_Edit_: I had been using `tut:silent` a lot and forgot that `tut` includes the `scala>` prompt in the output, so I wrote an irrelevant detail.

**Comment by tpolecat** [comment]
dammit

**Comment by zakpatterson** [comment]
I think fixing this would break my use case, where I would like to be able to guarantee that an expensive expression compiles for my document generation, but I don't want the calculation to run. 

```
... at the end of this great paragraph, we have this example code:
```tut:invisible
object compileNotRun{
``` 
```tut:book
bigSparkThing map veryExpensiveComputation
``` 
```tut:invisible
}
```  
```

(For @ceedubs: I wrapped the whole thing in a shed, but the parser will treat the closing shed you intend to have printed as closing the whole thing, but only if it's alone on a new line, so the closing `````s are followed by unicode 00A0 (non-breaking-space).  The parser also trims regular spaces from lines so just using a space key space doesn't work.)

**Comment by tpolecat** [comment]
Seems like a pretty specialized use case ... I'm inclined to say use a `def` or something if you don't want to evaluate an expression. Most of the time leaving one open is a bug.

**Comment by zakpatterson** [comment]
Sounds reasonable, think my doc would read ok with the example in a `def`. If the feature is ever supported it would make sense in its own Modifier
