### ISSUE TITLE
Feature: Cleaner output

### ISSUE THREAD

**Issue by noelwelsh** [tpolecat/tut#67]
To support copy and pasting code from our books we'd like cleaner output from Tut. Specifically:

- no console prompt cruft. No `scala>` and no `|` continuation character.
- console output is placed within comments

So

~~~ scala
object Foo {
  def foo(a: Int): Int = a + 1
}
~~~

renders as

~~~ scala
object Foo {
  def foo(a: Int): Int = a + 1
}
// defined module Foo
~~~

not

~~~ scala
scala> object Foo {
        |    def foo(a: Int): Int = a + 1
        |  }
defined module Foo
~~~

**Comment by tpolecat** [comment]
Ok, so kind of like `:silent` but with output shown (in comments). You also noted on gitter that it would be nice to have no output for imports (see also #25).

**Comment by tpolecat** [comment]
er, I mean see #56

**Comment by noelwelsh** [comment]
Yes, like `:silent` but with console output. And yes, suppressing output for `import` statements would be good.

**Comment by noelwelsh** [comment]
This has been implemented as the `:book` output format.
