### ISSUE TITLE
Link plugin to the sbt organization

### ISSUE THREAD

**Issue by InTheNow** [tpolecat/tut#71]
This will remove the need to specify the `tpolecat-sbt-plugin-releases` resolver

see http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization

**Comment by InTheNow** [comment]
And will also allow [4 LOC to be deleted from sbt-catalysts](https://github.com/InTheNow/sbt-catalysts/blob/master/build.sbt#L8-L11) that still have to be duplicated in client projects, eg [catalysts project](https://github.com/InTheNow/catalysts/blob/master/project/plugins.sbt#L1-L4)

**Comment by tpolecat** [comment]
It's a bit more complex because tut is actually two libraries: an sbt plugin, and a runtime that is added to your classpath and resolved via normal mechanisms. So we have to be sure that bit still works.

**Comment by InTheNow** [comment]
> It's a bit more complex because....

Isn't it always :wink: 

Seems to work in [catalysts](https://github.com/InTheNow/catalysts/blob/master/build.sbt#L164) (even if the produced product is minimal - http://inthenow.github.io/catalysts/ )

**Comment by InTheNow** [comment]
btw -  [code for generic use](https://github.com/InTheNow/sbt-catalysts/blob/master/src/main/scala/sbtcatalysts/CatalystsPlugin.scala#L329)

**Comment by InTheNow** [comment]
Implemented, tested and works :+1:
