### ISSUE TITLE
Workflow for copying generated Markdown files to the `gh-pages` branch

### ISSUE THREAD

**Issue by larsrh** [tpolecat/tut#91]
I'd like to be able to configure SBT in such a way that after the `tut` command is run, the generated Markdown files are committed to a (configurable?) folder in the `gh-pages` branch. The idea is that when that branch is pushed, GitHub Pages will run Jekyll on them. (As opposed to running Jekyll locally and pushing the results.)

@nebasuke asked me to open a ticket for this. Maybe we can work out the required configuration here.

**Comment by tpolecat** [comment]
Creating an empty branch and so on is a little mysterious so including all the `git` incantations would be helpful.

**Comment by nebasuke** [comment]
Thanks @larsrh. I should be able to do some work on this tomorrow evening and in the weekend.

**Comment by larsrh** [comment]
I think this is somewhat clear now. There are multiple possibilities, e.g. integrating with [sbt-site](https://github.com/sbt/sbt-site/) or using [sbt-microsites](https://github.com/47deg/sbt-microsites) which features native `tut` support.
